{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-opus",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.7.1.aar",
          "url": "media3-decode-opus-1.7.1.aar",
          "size": 513894,
          "sha512": "6aa76e2f446ffcb7f1d9398fc3fa3a9305026ea1aff9cfa5e55109d6f1efd529a82ba89bfee4bcc126a1b58526640df125db0a6dd1332ca4570d47647c3567fa",
          "sha256": "2c86965ef1a6c2d9b811c9798fb3aba39e6071acfdfd0da884a8f28a41108e2b",
          "sha1": "2e97dcd8b94a91ac4a30b55775045a861290429f",
          "md5": "03f1238dc0f35f445052de827ee1193b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.7.1.aar",
          "url": "media3-decode-opus-1.7.1.aar",
          "size": 513894,
          "sha512": "6aa76e2f446ffcb7f1d9398fc3fa3a9305026ea1aff9cfa5e55109d6f1efd529a82ba89bfee4bcc126a1b58526640df125db0a6dd1332ca4570d47647c3567fa",
          "sha256": "2c86965ef1a6c2d9b811c9798fb3aba39e6071acfdfd0da884a8f28a41108e2b",
          "sha1": "2e97dcd8b94a91ac4a30b55775045a861290429f",
          "md5": "03f1238dc0f35f445052de827ee1193b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-opus-1.7.1-sources.jar",
          "url": "media3-decode-opus-1.7.1-sources.jar",
          "size": 9397,
          "sha512": "7a0e31307fea6ead2a3e8e04edf5ab2594c1fa04007a5fcace3f2385e1e1ab8f537b498485e5f5f2a57705a66a64a88b3dab098de1f33dd41b26a22ec80346fd",
          "sha256": "c240deb746e60f92a69e0a9a4aa0da566b180286b3f24f282f59aa0c9266da4a",
          "sha1": "0c6df33ba6bbd2094f3c3e089dec97195b76c447",
          "md5": "caa1fa2425ba4ae79ca78c7ea320ecd2"
        }
      ]
    }
  ]
}
