{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-opus",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.7.1.aar",
          "url": "media3-decode-opus-1.7.1.aar",
          "size": 513701,
          "sha512": "db8fb5a5d62da0f1c4e83e9a1f9cf50898f69212cf14fdc5c47bf8e35262e17af18aa0abacf90db368de68c1bd18c50f8cad999443da6eb7871fea5c21f034e8",
          "sha256": "9fa85a5ed1a02837d39da1ad05d204af3abe5e188360acde834e2a95a5cd1a42",
          "sha1": "0141c1755a5506ab45c84b2c68bdad0771e4c737",
          "md5": "2344aab35624a10c9b094c93f7d89095"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.7.1.aar",
          "url": "media3-decode-opus-1.7.1.aar",
          "size": 513701,
          "sha512": "db8fb5a5d62da0f1c4e83e9a1f9cf50898f69212cf14fdc5c47bf8e35262e17af18aa0abacf90db368de68c1bd18c50f8cad999443da6eb7871fea5c21f034e8",
          "sha256": "9fa85a5ed1a02837d39da1ad05d204af3abe5e188360acde834e2a95a5cd1a42",
          "sha1": "0141c1755a5506ab45c84b2c68bdad0771e4c737",
          "md5": "2344aab35624a10c9b094c93f7d89095"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-opus-1.7.1-sources.jar",
          "url": "media3-decode-opus-1.7.1-sources.jar",
          "size": 9397,
          "sha512": "7a0e31307fea6ead2a3e8e04edf5ab2594c1fa04007a5fcace3f2385e1e1ab8f537b498485e5f5f2a57705a66a64a88b3dab098de1f33dd41b26a22ec80346fd",
          "sha256": "c240deb746e60f92a69e0a9a4aa0da566b180286b3f24f282f59aa0c9266da4a",
          "sha1": "0c6df33ba6bbd2094f3c3e089dec97195b76c447",
          "md5": "caa1fa2425ba4ae79ca78c7ea320ecd2"
        }
      ]
    }
  ]
}
