{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-vp9",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-vp9-1.8.0.aar",
          "url": "media3-decode-vp9-1.8.0.aar",
          "size": 862252,
          "sha512": "5a48effe9a1ff89090777b5c695671b09435a4beb8eb61011de1c413a58ae6f11d610994b096f19c62360731a26e5ae75bc28c4ab0ae0d856b495ec4302b3ff3",
          "sha256": "7f59e42c2f2d816400ee1b479ebe1e4a4360d4722c17ca9cbb76bc7af1a6ab0a",
          "sha1": "9f9afae923ff1aa6a8047c8ce44306390fd9c57b",
          "md5": "94939f8a69d0106d0d12c241d9a13505"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-vp9-1.8.0.aar",
          "url": "media3-decode-vp9-1.8.0.aar",
          "size": 862252,
          "sha512": "5a48effe9a1ff89090777b5c695671b09435a4beb8eb61011de1c413a58ae6f11d610994b096f19c62360731a26e5ae75bc28c4ab0ae0d856b495ec4302b3ff3",
          "sha256": "7f59e42c2f2d816400ee1b479ebe1e4a4360d4722c17ca9cbb76bc7af1a6ab0a",
          "sha1": "9f9afae923ff1aa6a8047c8ce44306390fd9c57b",
          "md5": "94939f8a69d0106d0d12c241d9a13505"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-vp9-1.8.0-sources.jar",
          "url": "media3-decode-vp9-1.8.0-sources.jar",
          "size": 8806,
          "sha512": "82e3da40998905603def4e85b3af47d12e12478e15d9e41f29c2526b5d6cf342a62f4c5363c271c74a23f4285182c00ab247f66266b2c4dbc3901ea17542b344",
          "sha256": "07d63e3a966d5ec1627ac25b81e6fad39fe6eaab5ab63b6e0d838ce504365c55",
          "sha1": "fce8af9544978db185c9941a8df3cde8c825bff2",
          "md5": "f7f4dba0240579719020bd4e4e675ebc"
        }
      ]
    }
  ]
}
