{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-opus",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.8.0.aar",
          "url": "media3-decode-opus-1.8.0.aar",
          "size": 511552,
          "sha512": "e3dbdb0b8427a41553d828192649c84b1ad805dffc26bd91d28ac0d5b7ccc1aafd1c3168e90e0b1c86b081348cb73a5b005129ec77704465fb7ec76abbda39ec",
          "sha256": "cc9e417ac304886d59035592f0ece8b977c4d063fc5987485482a1d43be2c014",
          "sha1": "fd489610cffd3f797611df2f47caa8f8487bc708",
          "md5": "83f5a81583c9f5eff5e9facf28f1f5e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.8.0.aar",
          "url": "media3-decode-opus-1.8.0.aar",
          "size": 511552,
          "sha512": "e3dbdb0b8427a41553d828192649c84b1ad805dffc26bd91d28ac0d5b7ccc1aafd1c3168e90e0b1c86b081348cb73a5b005129ec77704465fb7ec76abbda39ec",
          "sha256": "cc9e417ac304886d59035592f0ece8b977c4d063fc5987485482a1d43be2c014",
          "sha1": "fd489610cffd3f797611df2f47caa8f8487bc708",
          "md5": "83f5a81583c9f5eff5e9facf28f1f5e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-opus-1.8.0-sources.jar",
          "url": "media3-decode-opus-1.8.0-sources.jar",
          "size": 9397,
          "sha512": "7a0e31307fea6ead2a3e8e04edf5ab2594c1fa04007a5fcace3f2385e1e1ab8f537b498485e5f5f2a57705a66a64a88b3dab098de1f33dd41b26a22ec80346fd",
          "sha256": "c240deb746e60f92a69e0a9a4aa0da566b180286b3f24f282f59aa0c9266da4a",
          "sha1": "0c6df33ba6bbd2094f3c3e089dec97195b76c447",
          "md5": "caa1fa2425ba4ae79ca78c7ea320ecd2"
        }
      ]
    }
  ]
}
