{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-vp9",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-vp9-1.7.1.aar",
          "url": "media3-decode-vp9-1.7.1.aar",
          "size": 858732,
          "sha512": "71c1d3310f08807aeca20ac53da56936bf7a1d851b597683caa2baa8cf7b051748c9d737508f5885809c757a5ad2b12757ee169c95c534b779f9860791e88264",
          "sha256": "9e19e690f83ce298cd4cca755ce85c11645817e57351cf24efb6b481d1ce76b0",
          "sha1": "24978c0d5e3f16594c855858c44c25d66e2a2129",
          "md5": "dce8d2c74e80940dbd94c0dbc9df6f12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-vp9-1.7.1.aar",
          "url": "media3-decode-vp9-1.7.1.aar",
          "size": 858732,
          "sha512": "71c1d3310f08807aeca20ac53da56936bf7a1d851b597683caa2baa8cf7b051748c9d737508f5885809c757a5ad2b12757ee169c95c534b779f9860791e88264",
          "sha256": "9e19e690f83ce298cd4cca755ce85c11645817e57351cf24efb6b481d1ce76b0",
          "sha1": "24978c0d5e3f16594c855858c44c25d66e2a2129",
          "md5": "dce8d2c74e80940dbd94c0dbc9df6f12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-vp9-1.7.1-sources.jar",
          "url": "media3-decode-vp9-1.7.1-sources.jar",
          "size": 8806,
          "sha512": "82e3da40998905603def4e85b3af47d12e12478e15d9e41f29c2526b5d6cf342a62f4c5363c271c74a23f4285182c00ab247f66266b2c4dbc3901ea17542b344",
          "sha256": "07d63e3a966d5ec1627ac25b81e6fad39fe6eaab5ab63b6e0d838ce504365c55",
          "sha1": "fce8af9544978db185c9941a8df3cde8c825bff2",
          "md5": "f7f4dba0240579719020bd4e4e675ebc"
        }
      ]
    }
  ]
}
